# Sorting

In [1]:
import time
import numpy as np
np.random.seed(0)

In [2]:
data = np.random.randint(1,10000,17000)

### Insertion Sort

In [158]:
def insertion_sort(arr):
    start = time.time()
    for i in range(len(arr)):
        j=i
        while j>0 and arr[j-1]>arr[j]:
            cont=arr[j-1]
            arr[j-1]=arr[j]
            arr[j]=cont
            j=j-1
    end = time.time()
    print("The time of execution of above program is :", (end-start) * 10**3, "ms", "for a size of ", len(arr))
    return arr

In [159]:
arr= insertion_sort(data)

The time of execution of above program is : 3.986835479736328 ms for a size of  17000


In [160]:
arr

array([   1,    1,    2, ..., 9999, 9999, 9999])

### Merge Sort

In [152]:
#I used many methods, if you guys need more or less methods, feel free to change everything.
def merge(arr,left_arr,right_arr,mid_arr):
    #Auxiliar array
    new_arr = np.zeros(len(arr))
    left1=left_arr
    mid=mid_arr+1
    left2=left_arr
    while left1<=mid_arr and mid<=right_arr:
        if arr[left1]<arr[mid]:
            new_arr[left2]=arr[left1]
            left1+=1
        else:
            new_arr[left2]=arr[mid]
            mid+=1
        left2+=1
    while left1<=mid_arr:
        new_arr[left2]=arr[left1]
        left1+=1
        left2+=1
    while mid<=right_arr:
        new_arr[left2]=arr[mid]
        mid+=1
        left2+=1
    return new_arr
    #What's the complexity in space for Merge sort?
    #Merge, in this method I applied the actual merging.
    #I did it with the indices 

In [153]:
def merge_sort(arr,left,right):
    if left<right:
        merge_sort(arr,left, (left + right) // 2)
        merge_sort(arr,((left + right) // 2) +1, right)
        list_arr=merge(arr,left,right,(left + right) // 2)
        for i in range(left,right + 1):
            arr[i] = list_arr[i]

    return arr
    #This method will divide the array

In [150]:
#This method is just to calculate the time, if you don't need it, don't worry
def merge_algorithm(arr):
    start = time.time()
    merge_sort(arr,0,len(arr)-1)
    end = time.time()
    print("The time of execution of above program is :", (end-start) * 10**3, "ms", "for a size of ", len(arr))
    return arr

In [163]:
data = np.random.randint(1,1000,2000)
left = 0
right = len(data) - 1
start = time.time()
print(data)
arr= merge_sort(data,left,right)
end = time.time()
print(arr[:100])
print("The time of execution of above program is :", (end-start) * 10**3, "ms", "for a size of ", len(arr))

[181 375 828 ... 241  68 406]
[ 1  2  2  3  3  4  4  4  4  5  5  5  5  7  8  8  9  9 10 10 12 13 13 15
 16 16 18 18 19 20 21 21 22 22 23 24 25 25 25 26 26 27 27 27 28 28 28 28
 29 29 30 30 30 31 31 31 31 32 32 33 34 34 35 35 36 36 36 36 37 37 38 38
 39 40 40 41 41 42 42 43 43 44 44 44 45 46 47 47 49 49 49 50 50 53 55 55
 56 57 57 59]
The time of execution of above program is : 19.93250846862793 ms for a size of  2000


In [10]:
merge_algorithm(data)

The time of execution of above program is : 266.1881446838379 ms for a size of  17000


array([9180, 3146, 2272, ..., 6832, 1872, 2844])

### Algorithm of your choice

Know implement another algorithm, anyone works. Use the same size of data.

### Conclusions

So, the algorithm matters! Even when the result is the same, the time it takes is important. We are in the era of Big Data, if we are not careful, some processing might take centuries!