# Sorting

In [4]:
import time
import numpy as np
np.random.seed(0)

In [5]:
data = np.random.randint(1,10000,17000)

### Insertion Sort

In [8]:
def insertion_sort(arr):
    start = time.time()
    for i in range(len(arr)):
        j=i
        while j>0 and arr[j-1]>arr[j]:
            cont=arr[j-1]
            arr[j-1]=arr[j]
            arr[j]=cont
            j=j-1
    end = time.time()
    print("The time of execution of above program is :", (end-start) * 10**3, "ms", "for a size of ", len(arr))
    return arr

In [9]:
arr= insertion_sort(data)

The time of execution of above program is : 0.0 ms for a size of  17000


In [10]:
arr

array([   1,    1,    1, ..., 9999, 9999, 9999])

### Merge Sort

In [11]:

def merge(arr,left_arr,right_arr,mid_arr):
    #Auxiliar array
    new_arr = np.zeros(len(arr))
    left1=left_arr
    mid=mid_arr+1
    left2=left_arr
    while left1<=mid_arr and mid<=right_arr:
        if arr[left1]<arr[mid]:
            new_arr[left2]=arr[left1]
            left1+=1
        else:
            new_arr[left2]=arr[mid]
            mid+=1
        left2+=1
    while left1<=mid_arr:
        new_arr[left2]=arr[left1]
        left1+=1
        left2+=1
    while mid<=right_arr:
        new_arr[left2]=arr[mid]
        mid+=1
        left2+=1
    return new_arr
    #What's the complexity in space for Merge sort?
    #O(nlog(n))
    #Merge, in this method I applied the actual merging.

In [12]:
def merge_sort(arr,left,right):
    if left<right:
        merge_sort(arr,left, (left + right) // 2)
        merge_sort(arr,((left + right) // 2) +1, right)
        list_arr=merge(arr,left,right,(left + right) // 2)
        for i in range(left,right + 1):
            arr[i] = list_arr[i]

    return arr
    #This method will divide the array

In [13]:
#This method is just to calculate the time, if you don't need it, don't worry
def merge_algorithm(arr):
    start = time.time()
    merge_sort(arr,0,len(arr)-1)
    end = time.time()
    print("The time of execution of above program is :", (end-start) * 10**3, "ms", "for a size of ", len(arr))
    return arr

In [14]:

print("Data:")
print(data)
arr=merge_algorithm(data)
print("sorted data:")
print(arr)

Data:
[   1    1    1 ... 9999 9999 9999]
The time of execution of above program is : 159.93547439575195 ms for a size of  17000
sorted data:
[   1    1    1 ... 9999 9999 9999]


In [15]:
merge_algorithm(data)

The time of execution of above program is : 152.0097255706787 ms for a size of  17000


array([   1,    1,    1, ..., 9999, 9999, 9999])

### Algorithm of your choice

Know implement another algorithm, anyone works. Use the same size of data.

In [6]:
#QuickSort
def quicksort(arr,left, right):
    if left < right:
        indiceParticion = particion(arr, left, right)
        quicksort(arr, left, indiceParticion)
        quicksort(arr, indiceParticion + 1, right)

def particion(arr, left, right):
    pivote = arr[left]
    while True:
        # Mientras cada elemento desde la izquierda esté en orden (sea menor que el pivote) continúa avanzando el índice
        # As long as each element from the left is in order (be less than the pivot) continues to advance the index
        while arr[left] < pivote:
            left += 1

        # Mientras cada elemento desde la derecha esté en orden (sea mayor que el pivote) continúa disminuyendo el índice
        # As long as each element from the right is in order (is greater than the pivot) continues to decline the index
        while arr[right] > pivote:
            right -= 1

        """
            Si la izquierda es mayor o igual que la derecha significa que nonecesitamos hacer ningún intercambio
            de variables, pues los elementos ya están en orden (al menos en estaiteración)

            If the left is greater than or equal to the right it means that we do not need to do any exchange 
            of variables, because the elements are already in order (at least in this iteration)
        """
        if left >= right:
            # Indicar "en dónde nos quedamos" para poder dividir el arreglo de nuevo y ordenar los demás elementos
            # Indicate "where we stay" to be able to divide the arrangement again and order the other elements
            return right
        else:
            # Nota: yo sé que el else no hace falta por el return de arriba, pero así el algoritmo es más claro
            # Note: I know that the else is not needed by the return above, but this way the algorithm is clearer
            """
                Si las variables quedaron "lejos" (es decir, la izquierda no superó ni alcanzó a la derecha) significa
                que se detuvieron porque encontraron un valor que no estabaen orden, así que lo intercambiamos

                If the variables were "far away" (i.e. the left did not overcome or reach the right) it means that 
                they stopped because they found a value that was not in order, so we exchanged it
            """
            arr[left], arr[right] = arr[right], arr[left]
            """
                Ya intercambiamos, pero seguimos avanzando los índices
                We already exchanged, but we continue to advance the indices
            """
            left += 1
            right -= 1


print("Antes de ordenarlo: ")
print(data)
quicksort(data, 0, len(data) - 1)
print("Después de ordenarlo: ")
print(data)

Antes de ordenarlo: 
[2733 9846 3265 ... 7788 4911 5875]
Después de ordenarlo: 
[   1    1    1 ... 9999 9999 9999]


### Conclusions

So, the algorithm matters! Even when the result is the same, the time it takes is important. We are in the era of Big Data, if we are not careful, some processing might take centuries!